  name: "GitHub Docker Action"
  uses: matootie/github-docker@v2.2.2
  with: 
    accessToken: fa8e1fe7cca16440f2daf388c16318c01759e5ea
    buildArgs: ~
    context: ~
    imageName: ~
    imageTag: ~
    imageTagPrefix: ~
    imageTagSuffix: ~
    repositoryName: ~
    username: ~
